### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by sakufo** [osixia/docker-keepalived#10]
docker run --volume /data/keepalived.conf:/container/service/keepalived/assets/keepalived.conf osixia/keepalived:1.3.9 

*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/keepalived/startup.sh to /container/run/startup/keepalived
*** link /container/service/keepalived/process.sh to /container/run/process/keepalived/run
*** link /container/service/keepalived/finish.sh to /container/run/process/keepalived/finish
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/keepalived...
sed: can't move '/container/service/keepalived/assets/keepalived.confALkEhK' to '/container/service/keepalived/assets/keepalived.conf': Resource busy
*** /container/run/startup/keepalived failed with status 1

*** Running /container/run/process/keepalived/finish...
*** Killing all processes...

**Comment by BertrandGouny** [comment]
Hello,
try to run the container with `--copy-service` argument
please refer to the [README.md](https://github.com/osixia/docker-keepalived#fix-docker-mounted-file-problems) for more information
