### ISSUE TITLE
when system reboot or unexpected shutdown, keepalived never start up again

### ISSUE THREAD

**Issue by BloodyKnight** [osixia/docker-keepalived#18]
reproduce step((assume the container name is keepalived):
1.docker kill keepalived
2.docker start keeplaived
3.docker logs -f keepalived

logs:
*** ------------------------------------------
*** Running /container/run/process/keepalived/run...
*** /container/run/process/keepalived/run started as PID 25
Mon May 28 14:51:33 2018: Starting Keepalived v1.4.2 (02/24,2018), git commit v1.4.1-41-g6a2987e+
Mon May 28 14:51:33 2018: WARNING - keepalived was build for newer Linux 4.4.6, running on Linux3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017
Mon May 28 14:51:33 2018: Opening file '/usr/local/etc/keepalived/keepalived.conf'.
Mon May 28 14:51:33 2018: daemon is already running
*** /container/run/process/keepalived/run exited with status 0
*** Run commands before finish...
*** Running /container/run/process/keepalived/finish...
*** ------------ Environment dump ------------
*** KEEPALIVED_PRIORITY = 150
*** LC_CTYPE = C.UTF-8
*** INITRD = no
*** HOME = /root
*** PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
*** LANG = en_US.UTF-8
*** CONTAINER_SERVICE_DIR = /container/run/service
*** LANGUAGE = en_US:en
*** KEEPALIVED_VIRTUAL_IPS_ROW_2 = 192.168.1.232
*** KEEPALIVED_NOTIFY = /container/service/keepalived/assets/notify.sh
*** KEEPALIVED_COMMAND_LINE_ARGUMENTS = --log-detail --dump-conf
*** KEEPALIVED_VIRTUAL_IPS_ROW_1 = 192.168.1.231
*** KEEPALIVED_UNICAST_PEERS = #COMPLEX_BASH_ENV:TABLE: KEEPALIVED_UNICAST_PEERS_ROW_1 KEEPALIVED_UNICAST_PEERS_ROW_2
*** CONTAINER_LOG_LEVEL = 4
*** LC_ALL = en_US.UTF-8
*** KEEPALIVED_VIRTUAL_IPS = #COMPLEX_BASH_ENV:TABLE: KEEPALIVED_VIRTUAL_IPS_ROW_1 KEEPALIVED_VIRTUAL_IPS_ROW_2
*** KEEPALIVED_INTERFACE = eth0
*** KEEPALIVED_UNICAST_PEERS_ROW_1 = 192.168.1.10
*** KEEPALIVED_UNICAST_PEERS_ROW_2 = 192.168.1.11
*** HOSTNAME = localhost.localdomain
*** CONTAINER_STATE_DIR = /container/run/state
*** KEEPALIVED_PASSWORD = d0cker
*** ------------------------------------------
*** Killing all processes...

docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:05 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:05:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

hint:  is the keepalived pid fille caused this problem?

**Comment by qq12157138** [comment]
I also found this problem. When the system is restarted, docker-keepalived will not restart automatically.
