### ISSUE TITLE
Question: Why state is hard coded to BACKUP?

### ISSUE THREAD

**Issue by saqibahmed515** [osixia/docker-keepalived#19]
In the default `keepalived.conf` file, the state has been hardcoded to `BACKUP`. Shouldn't there be an environment variable to decide the state of the node?

<pre>
...
vrrp_instance VI_1 {
  interface {{ KEEPALIVED_INTERFACE }}

  track_interface {
    {{ KEEPALIVED_INTERFACE }}
  }

  <b>state BACKUP</b>
  virtual_router_id {{ KEEPALIVED_ROUTER_ID }}
  priority {{ KEEPALIVED_PRIORITY }}
  nopreempt
...
</pre>

**Comment by BertrandGouny** [comment]
In our use case this was not necessary but if you need one sure.
Pull request welcome :)
