### ISSUE TITLE
How to use the keepalived with  docker-compose.yml?

### ISSUE THREAD

**Issue by T1Nk1r** [osixia/docker-keepalived#23]
Docker version 18.03.1-ce, build 9ee9f40
docker-compose version 1.21.2, build a133471
docker-compose.yml version 3.6
![yml](https://user-images.githubusercontent.com/40633297/42071975-d0436d56-7b90-11e8-89a5-aa4eb1fb28a0.PNG)
![running1](https://user-images.githubusercontent.com/40633297/42072046-2b13fffc-7b91-11e8-802d-d45b4fbbe506.PNG)
the keepalived image built by https://github.com/osixia/docker-keepalived/tree/stable/image
what should i do?Give me some advice,plz!
Forgive me the poor English!

**Comment by meyayl** [comment]
You will need to add the required capabilites like this: https://docs.docker.com/compose/compose-file/#cap_add-cap_drop

Though, for time beeing this is only supported for docker-compose deployment, but not for swarm service/stack deployments (see: https://github.com/moby/moby/issues/25885)
