### ISSUE TITLE
Netlink: error: Operation not permitted(1), type=RTM_NEWADDR(20), seq=1563327313, pid=0

### ISSUE THREAD

**Issue by guang0204** [osixia/docker-keepalived#31]
docker image ，How to solve this problem？

**Comment by guang0204** [comment]
权限问题导致的

**Comment by daveteu** [comment]
什么权限？

**Comment by pshizhsysu** [comment]
权限不够，需要添加NET_ADMIN, NET_BROADCAST，NET_RAW
比如：
1、用docker运行
docker run --cap-add=NET_ADMIN --cap-add=NET_BROADCAST --cap-add=NET_RAW ....

2、用k8s的Pod运行
apiVersion: v1
kind: Pod
metadata:
  name: xxx
spec:
  containers:
  - name: keepalived
    image: xxxxx
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "NET_BROADCAST", "NET_RAW"]
...
