### ISSUE TITLE
Reload configuration

### ISSUE THREAD

**Issue by orenye** [osixia/docker-keepalived#38]
Hi,

Is there a way to reload the configuration without restating the container (the same as done in the not dockerized version with: _systemctl reload keepalived_).

Thanks

**Comment by linkvt** [comment]
Hi @orenye,
you should be able to do this by sending the HUP signal to the process, many applications support this, see https://manpages.debian.org/testing/keepalived/keepalived.8.en.html#SIGNALS
```
kill -HUP $(cat /var/run/keepalived.pid)
```

@BertrandGouny ticket can be closed.

**Comment by orenye** [comment]
Thanks @linkvt, yes you are right. I figured it out back then but other priorities distracted me from this issue and I didn't check it.
