### ISSUE TITLE
error:can not move conf file

### ISSUE THREAD

**Issue by xchkun** [osixia/docker-keepalived#5]
when i run "docker run -itd --name keepalived --cap-add=NET_ADMIN  --net host -v  /root/keepalived/keepalived.conf:/container/service/keepalived/assets/keepalived.conf   osixia/keepalived" docker logs containerId as follow:
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/keepalived/startup.sh to /container/run/startup/keepalived
*** link /container/service/keepalived/process.sh to /container/run/process/keepalived/run
*** link /container/service/keepalived/finish.sh to /container/run/process/keepalived/finish
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/keepalived...
sed: can't move '/container/service/keepalived/assets/keepalived.confHBCjcp' to '/container/service/keepalived/assets/keepalived.conf': Resource busy
*** /container/run/startup/keepalived failed with status 1

*** Running /container/run/process/keepalived/finish...
*** Killing all processes...

**Comment by osixia** [comment]
Running the container with --copy-service should solve this issue.

**Comment by julienbonastre** [comment]
I mean, that secret argument is cute and all, but doesn't really help beyond local/dev/testing use-cases if one desires to use this in any form of CasC/IaC/Compose orientated mature solution...
